// ---------------------------------------------------------------------------
// Chinese (Simplified) names for all 118 cities and 77 provinces.
// Used by getCityName / getProvinceName / getCityTagline in cityPresentation.ts
// when locale === "zh". Falls back to English when a key is absent.
// ---------------------------------------------------------------------------

/** Province English name → Simplified Chinese */
export const PROVINCE_ZH: Record<string, string> = {
  // Bangkok
  "Bangkok": "曼谷",
  // Central
  "Ang Thong": "红统府",
  "Ayutthaya": "大城府",
  "Chainat": "猜纳府",
  "Chachoengsao": "北柳府",
  "Kanchanaburi": "北碧府",
  "Lop Buri": "华富里府",
  "Nakhon Nayok": "那空那育府",
  "Nakhon Pathom": "那空巴吞府",
  "Nakhon Sawan": "那空沙旺府",
  "Nonthaburi": "暖武里府",
  "Pathum Thani": "巴吞他尼府",
  "Phetchaburi": "碧武里府",
  "Prachuap Khiri Khan": "巴蜀府",
  "Ratchaburi": "叻武里府",
  "Samut Prakan": "北揽府",
  "Samut Sakhon": "沙没沙坤府",
  "Samut Songkhram": "沙没颂堪府",
  "Saraburi": "沙拉武里府",
  "Sing Buri": "信武里府",
  "Suphan Buri": "素攀府",
  // North
  "Chiang Mai": "清迈府",
  "Chiang Rai": "清莱府",
  "Kamphaeng Phet": "甘烹碧府",
  "Lampang": "南邦府",
  "Lamphun": "南奔府",
  "Mae Hong Son": "湄宏顺府",
  "Nan": "难府",
  "Phayao": "帕尧府",
  "Phetchabun": "碧差汶府",
  "Phichit": "披集府",
  "Phitsanulok": "彭世洛府",
  "Phrae": "帕府",
  "Sukhothai": "素可泰府",
  "Tak": "达府",
  "Uthai Thani": "乌泰他尼府",
  "Uttaradit": "乌泰他尼府",
  // Northeast (Isan)
  "Amnat Charoen": "阿默那察隆府",
  "Bueng Kan": "汶坎府",
  "Buriram": "武里南府",
  "Chaiyaphum": "猜也奔府",
  "Kalasin": "迦拉信府",
  "Khon Kaen": "孔敬府",
  "Loei": "黎府",
  "Maha Sarakham": "马哈沙拉堪府",
  "Mukdahan": "慕达汉府",
  "Nakhon Phanom": "那空帕农府",
  "Nakhon Ratchasima": "呵叻府",
  "Nong Bua Lamphu": "农宝浪蒲府",
  "Nong Khai": "廊开府",
  "Roi Et": "黎逸府",
  "Sakon Nakhon": "色军府",
  "Sisaket": "四色菊府",
  "Surin": "素林府",
  "Ubon Ratchathani": "乌汶府",
  "Udon Thani": "乌隆他尼府",
  "Yasothon": "耶梭通府",
  // East
  "Chanthaburi": "尖竹汶府",
  "Chon Buri": "春武里府",
  "Prachin Buri": "巴真武里府",
  "Rayong": "罗勇府",
  "Sa Kaeo": "沙缴府",
  "Trat": "达叻府",
  // South
  "Chumphon": "春蓬府",
  "Krabi": "甲米府",
  "Nakhon Si Thammarat": "洛坤府",
  "Narathiwat": "那拉提瓦府",
  "Pattani": "北大年府",
  "Phang Nga": "攀牙府",
  "Phatthalung": "博他仑府",
  "Phuket": "普吉府",
  "Ranong": "拉廊府",
  "Satun": "沙敦府",
  "Songkhla": "宋卡府",
  "Surat Thani": "素叻他尼府",
  "Trang": "董里府",
  "Yala": "惹拉府",
};

/** City ID → Simplified Chinese display name */
export const CITY_NAME_ZH: Record<string, string> = {
  // ─── CERTIFIED BATCH 1 (2021) ───
  "chiang-mai-old-town": "清迈古城智慧城市",
  "cmu-smart-city": "清迈大学智慧城市",
  "mae-moh": "湄末宜居城市",
  "nakhonsawan": "那空沙旺智慧城市",
  "khon-kaen": "孔敬智慧城市",
  "samyan": "三眼井智慧城市",
  "phra-ram-4": "四世皇路智慧城市",
  "klong-phadung": "巴东运河智慧城市",
  "makkasan": "马卡山智慧城市",
  "chachoengsao": "北柳智慧城市",
  "saensuk": "桑素智慧城市",
  "wangchan-valley": "旺湛谷智慧城市",
  "phuket": "普吉智慧城市",
  "sritrang": "斯里廊城市",
  "yala": "惹拉智慧城市",
  // ─── CERTIFIED BATCH 2 (2022) ───
  "rayong": "罗勇智慧城市",
  "khao-khun-song": "考坤颂智慧城市",
  "phitsanulok-muni": "彭世洛市政智慧城市",
  "phitsanulok-nu": "那莱大学智慧城市",
  "chiang-rai": "清莱智慧城市",
  "nan": "难智慧城市",
  "korat": "呵叻智慧城市",
  "ubon": "乌汶拉差他尼智慧城市",
  "krabi": "甲米智慧城市",
  "phangnga": "攀牙智慧城市",
  "satun": "沙敦智慧城市",
  "samui": "苏梅岛智慧城市",
  "hat-yai": "合艾智慧城市",
  "pattani": "北大年智慧城市",
  "narathiwat": "那拉提瓦智慧城市",
  // ─── CERTIFIED BATCH 3 (2023) ───
  "lampang": "南邦智慧城市",
  "samut-prakan": "北揽智慧城市",
  "thep-paraj": "乍班智慧城市",
  "nikhom-phatthana": "尼空帕他那智慧城市",
  "nakhon-si-thammarat": "洛坤智慧城市",
  "tai-yong": "泰勇智慧城市",
  // ─── CERTIFIED BATCH 4 (2025) ───
  "phuket-tinicon": "普吉廷尼肯谷",
  // ─── PROMOTION ZONES ───
  "songkhla-city": "宋卡城市",
  "rattanakosin": "拉达那哥辛智慧区",
  "nonthaburi": "暖武里智慧城市",
  "chanthaburi": "尖竹汶智慧城市",
  "tak": "达智慧城市",
  "phichit": "披集智慧城市",
  "umong": "乌蒙智慧城市",
  "maesai": "湄赛智慧城市",
  "bang-saray": "邦萨雷智慧城市",
  "phitsanulok-ppao": "彭世洛府智慧城市",
  "ubon-muni": "乌汶拉差他尼市政智慧城市",
  "phlapphla": "帕普拉那拉智慧城市",
  // ─── REGISTERED — NORTH ───
  "reg-chiang-mai-pao": "清迈府行政组织",
  "reg-lamphun": "南奔市政府",
  "reg-lampang-pao": "南邦府行政组织",
  "reg-uttaradit": "乌泰他尼市政府",
  "reg-sukhothai": "素可泰市政府",
  "reg-phrae": "帕市政府",
  "reg-phayao": "帕尧市政府",
  "reg-mae-hong-son": "湄宏顺市政府",
  "reg-kamphaeng-phet": "甘烹碧市政府",
  "reg-uthai-thani": "乌泰他尼市政府",
  "reg-nakhon-sawan-pao": "那空沙旺府行政组织",
  "reg-phetchabun": "碧差汶市政府",
  // ─── REGISTERED — CENTRAL ───
  "reg-ayutthaya": "大城府",
  "reg-pathum-thani": "巴吞他尼市政府",
  "reg-nakhon-pathom": "那空巴吞市政府",
  "reg-samut-sakhon": "沙没沙坤市政府",
  "reg-samut-songkhram": "沙没颂堪市政府",
  "reg-ang-thong": "红统市政府",
  "reg-singburi": "信武里市政府",
  "reg-lop-buri": "华富里市政府",
  "reg-saraburi": "沙拉武里市政府",
  "reg-chainat": "猜纳市政府",
  "reg-suphan-buri": "素攀府市政府",
  "reg-kanchanaburi": "北碧市政府",
  "reg-ratchaburi": "叻武里市政府",
  "reg-phetchaburi": "碧武里市政府",
  "reg-prachuap": "巴蜀府",
  "reg-hua-hin": "华欣市政府",
  // ─── REGISTERED — NORTHEAST ───
  "reg-udon-thani": "乌隆他尼市政府",
  "reg-nong-khai": "廊开市政府",
  "reg-sakon-nakhon": "色军市政府",
  "reg-nakhon-phanom": "那空帕农市政府",
  "reg-mukdahan": "慕达汉市政府",
  "reg-roi-et": "黎逸市政府",
  "reg-kalasin": "迦拉信市政府",
  "reg-maha-sarakham": "马哈沙拉堪市政府",
  "reg-chaiyaphum": "猜也奔市政府",
  "reg-buriram": "武里南市政府",
  "reg-surin": "素林市政府",
  "reg-sisaket": "四色菊市政府",
  "reg-amnat-charoen": "阿默那察隆市政府",
  "reg-yasothon": "耶梭通市政府",
  "reg-loei": "黎府市政府",
  "reg-nong-bua-lamphu": "农宝浪蒲市政府",
  "reg-bueng-kan": "汶坎市政府",
  // ─── REGISTERED — EAST ───
  "reg-chon-buri-muni": "春武里市政府",
  "reg-pattaya": "芭提雅城市",
  "reg-sri-racha": "斯里拉查市政府",
  "reg-trat": "达叻市政府",
  "reg-sa-kaeo": "沙缴市政府",
  "reg-prachin-buri": "巴真武里市政府",
  "reg-nakhon-nayok": "那空那育市政府",
  // ─── REGISTERED — SOUTH ───
  "reg-surat-thani": "素叻他尼市政府",
  "reg-nakhon-si-pao": "洛坤府行政组织",
  "reg-chumphon": "春蓬市政府",
  "reg-ranong": "拉廊市政府",
  "reg-phatthalung": "博他仑市政府",
  "reg-songkhla-pao": "宋卡府行政组织",
  "reg-phuket-pao": "普吉府行政组织",
  "reg-krabi-muni": "甲米市政府",
  "reg-trang-muni": "董里市政府",
  "reg-yala-pao": "惹拉府行政组织",
  "reg-pattani-muni": "北大年市政府",
  "reg-narathiwat-muni": "那拉提瓦市政府",
  // ─── REGISTERED — BANGKOK ───
  "reg-bangkok-noi": "曼谷诺区",
  "reg-bang-rak": "曼谷叻区",
  "reg-din-daeng": "丁当区",
  "reg-chatuchak": "恰图恰区",
  "reg-bang-sue": "曼谷素区",
};

/** City ID → Simplified Chinese tagline (certified cities only) */
export const CITY_TAGLINE_ZH: Record<string, string> = {
  "chiang-mai-old-town": "北部文化心脏。以遗产保护技术和数字旅游驱动的真实智慧城市，但受季节性雾霾制约。",
  "cmu-smart-city": "大学校园即活体实验室。具备智能电网、AI交通和开放数据平台的真正研发引擎。",
  "mae-moh": "正在向清洁能源转型的煤矿城市。智慧能源监测属实，但工业遗产带来的宜居挑战依然存在。",
  "nakhonsawan": "四河汇流之地。世界银行CCDR 2025：昭披耶河流域占泰国40%人口、78%劳动力、66% GDP——目前的120年一遇洪水到2040年可能每18年发生一次。这里的物联网洪水传感器是国家经济的生命线。",
  "khon-kaen": "泰东北经济首府。世界银行CCDR 2025专项调研城市，发现其水资源韧性障碍是制度性的而非技术性的——地方政府权限有限，无法开展综合省级水规划。轻轨和智慧公交属实，水治理缺口同样属实。",
  "samyan": "曼谷功能最完善的智慧区，也是最积极应对气候尾部风险的区域。BMA 2024年城市热管理框架（27°C至52°C+四阶段预警）、植树200万棵、15分钟公园计划——曼谷应对气候变化的意志在此凝聚。",
  "phra-ram-4": "曼谷CBD走廊，智慧基础设施投资与气候适应正在交汇。世界银行2025年将IconSiam高架结构设计列为私营部门气候韧性的早期证据。曼谷每十万人道路死亡率为14，是泰国最低的。",
  "klong-phadung": "历史运河区以智慧水务管理和互联公共空间重获新生。真实的城市更新项目。",
  "makkasan": "大型交通枢纽规划停留在纸面。几乎什么都没建成。土地在那里，但智慧城市不在——又一个等待落地的计划。",
  "chachoengsao": "EEC门户城市，拥有真实智慧基础设施——世界银行CCDR 2025：北柳府是EEC三省中预计水资源缺口最大的省份（到2037年达8.97亿立方米）。这里的智慧洪水预警系统不是可选项目，而是最重要的运营系统。",
  "saensuk": "真正运转的海滨市政府。智慧废物管理和海滩水质监测均已运行。规模小但货真价实。",
  "wangchan-valley": "泰国纸面排名第一的智慧城市。PTT的3454莱EEC园区，VISTEC和KVIS已运营，但生物炼油厂延期两年，公开的住宅入住率为零。世界银行2025：EEC到2037年面临40%供水短缺——旺湛谷的发展愿景建立在尚不存在的水安全之上。",
  "phuket": "泰国功能最完善的智慧旅游城市。世界银行CCDR 2025点名指出其热应激脆弱性将缩短户外旅游季。695家酒店加入泰旅局CF-Hotels平台，但仅160家于2024年自报排放数据。海岸度假村正在联合出资修复红树林。",
  "sritrang": "宁静的南部城市，拥有真实的绿色举措。智慧农业和环境监测有效运行。诚实的小规模智慧城市。",
  "yala": "南部冲突区的智慧城市。尽管面临安全挑战，仍取得令人印象深刻的绿色城市成就。荣获智慧环境卓越奖。",
  "rayong": "EEC工业重镇，泰国人均GPP最高省份。世界银行CCDR 2025：罗勇供水缺口将从2024年的1.7亿立方米增至2037年的2.92亿立方米，仅37%的EEC废水得到处理。水循环利用是这条走廊的下一个竞争优势。",
  "khao-khun-song": "小型智慧农业区。部分数字农业技术已部署，但仍处于非常早期的阶段。",
  "phitsanulok-muni": "下北部枢纽，拥有真实的智慧治理。数字公民服务运转良好。朴实无华却真正交付成果的智慧城市。",
  "phitsanulok-nu": "以能源和出行研究为重点的大学校园智慧城市。产出真实的研发成果。",
  "chiang-rai": "最北端的智慧城市，拥有文化旅游科技。燃烧季的空气质量危机是不可回避的问题。",
  "nan": "小型北部城市，拥有真实的社区驱动智慧举措。森林保护技术和遗产保护均属实。",
  "korat": "泰东北门户城市，拥有真实的智慧交通雄心。与高铁项目相连。潜力巨大，势头仍在积累中。",
  "ubon": "湄公河边境城市，文化丰厚。智慧举措聚焦洪水管理和文化旅游。真实但仍处早期阶段。",
  "krabi": "安达曼旅游中心，被世界银行CCDR 2025点名提及两件事：热应激脆弱性；以及奈囊养蜂项目——红树林修复与养蜂结合、获万豪酒店支持并在餐厅销售蜂蜜的自然海岸保护模式。",
  "phangnga": "具有真实灾害管理技术的海啸感知智慧城市。环境监测和预警系统运行属实。",
  "satun": "联合国教科文组织地质公园智慧城市。真实的环境技术用于地质遗产保护。小而宁静，真实可信。",
  "samui": "拥有旅游科技的岛屿智慧城市。真实的智慧废物和水务管理，正是这座岛屿迫切需要的。旅游压力巨大。",
  "hat-yai": "南部商业中心，拥有真实的智慧城市基础设施。智慧防洪管理对这座易涝城市至关重要。",
  "pattani": "面临安全挑战的南部深度智慧城市。数字治理和安全系统是在艰难处境中改善局面的真诚努力。",
  "narathiwat": "最南端的智慧城市，拥有真实的跨境数字贸易试点。安全局势严重制约宜居成果。",
  "lampang": "马车城市走向智慧化。真实的遗产科技融合，来自湄末煤电转型的智慧能源。空气质量依然是未解决的问题。",
  "samut-prakan": "曼谷工业郊区，拥有智慧工厂技术。制造业真实采用工业4.0。宜居性因拥堵和洪涝而受损。",
  "thep-paraj": "北柳府EEC小型子区——EEC三省中预计水资源缺口最大。这里的智慧农业物联网不只是为了提高产量：在面临60%以上供水缺口的地区，水效率是生存条件。",
  "nikhom-phatthana": "毗邻玛塔普特的工业区。环境监测至关重要。世界银行CCDR 2025：罗勇到2037年面临2.92亿立方米水资源缺口，仅37%的EEC废水得到处理。对于石化工业区而言，水循环利用不是可选项。",
  "nakhon-si-thammarat": "拥有真实防洪技术的古城。真实的智慧治理和遗产保护。SLIC的大本营。",
  "tai-yong": "小型子区智慧城市。社区规模的数字治理和农业技术。真实但规模很小。",
  "phuket-tinicon": "最新认证城市——但这是一个发展规划，而非运转中的城市。徽标授予了一个概念。",
  "bang-saray": "芭提雅附近的沿海社区，拥有渔村智慧科技。规模不大，但数字治理真实可信。",
  "phitsanulok-ppao": "覆盖整个披集洛府的省级智慧治理。数字服务延伸至农村地区。",
  "songkhla-city": "拥有真实智慧治理和旅游科技的历史湖城。文化认同深厚。",
  "ubon-muni": "配合更大规模乌汶项目的市级智慧城市。聚焦蜡烛节旅游科技。",
};
